### PR TITLE
Pass repository details to spawned process via environment

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by schickling** [comment]
@MartinThoma could you do a quick review please?

**Comment by MartinThoma** [comment]
Looks ok (without having it run)

There are two changes:
- [`subprocess.Popen`](https://docs.python.org/2/library/subprocess.html#subprocess.Popen) instead of `os.system`: This is probably rather the way to go as subprocess is more flexible (e.g. http://stackoverflow.com/q/4813238/562769 ... I guess I should write a better answer there...)
- Reading the payload as JSON and setting the suprocesses environment accordingly. I am not familiar with `BaseHTTPRequestHandler`, but it looks like http://stackoverflow.com/a/17888592/562769 so it's probably fine. However, I am not sure what happens when you don't have payload. I am also not sure if setting the `env` parameter just overwrites existing environment variables or if it is then the only environment variable active (hence overwriting all environment variables for this process)

**Comment by tristan0x** [comment]
@MartinThoma Thanks for taking the time to look at it.
You are right about the 2 following points:
- Parent environment is wiped out. I will fix that.
- `json` module raises a `ValueError` exception is payload is empty. I will also fix that.

Thanks again for the review

**Comment by schickling** [comment]
Thanks @MartinThoma for the code review and thanks @tristan0x for the pull request.

**Pull request merged**
